name: pet_widget
description: Widget tracker for pets

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.3.0
  material_design_icons_flutter: ^7.0.7296
  home_widget: ^0.7.0+1
  file_picker: ^10.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFB400"
  color_dark: "#FFB400"
  android: true
  ios: true
