name: pet_widget
description: Widget tracker for pets

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  http: ^1.2.1
  material_design_icons_flutter: ^7.0.7296
  home_widget: ^0.6.0
  file_picker: 8.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFB400"
  color_dark: "#FFB400"
  android: true
  ios: true
